version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: xpresent_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: xpresent
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: bitnami/redis:7.2
    container_name: xpresent_redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=bgWamssDMT
      - REDIS_PORT_NUMBER=6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "bgWamssDMT", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
